### PR TITLE
removed the dependency on OpenMP

### LINKED ISSUE #2: OpenMP not needed
Your CMakeLists.txt file requires OpenMP to be installed (line 6 and 11).  If both of those lines are commented out everything compiles nicely.  Those lines were causing `pip install lapsolver` to fail on macOS.  It seems you are not using OpenMP so those lines are extraneous, right?

### PR DESCRIPTION
**Pull request by ktarplee**
Closes #2

### CODE REVIEW

**Comment by cheind** [comment]
hey there! Thanks for the PR. 
 - Could you please base your PR on the develop branch (should be just a dropdown select on your side)? 
 - If we disable OpenMP things will be slower (I hope ;) on multicore CPUs. So we should make this optional. One way would be to perform 

```
find_package(OpenMP QUIET)

if(OpenMP_FOUND)
  message("Compiling with OpenMP support")
  target_compile_options(lapsolverc PUBLIC "$<$<CONFIG:RELEASE>:${OpenMP_CXX_FLAGS}>")
else()
  message("Compiling without OpenMP support")
endif()
```

So people having OpenMP installed would benefit from the parallelization, while the library still compiles for others.

**Comment by cheind** [comment]
In the meantime I will have a look why the appveyor build fails.

**Comment by ktarplee** [comment]
What code is actually using OpenMP?  I did not find any "#pragma omp" lines in your code?

**Comment by cheind** [comment]
Oh you are correct, it seems like I have dropped OpenMP support myself and forgot about the CMakeLists file. My bad!

**Comment by cheind** [comment]
merged to develop. Hopefully have time soon to make a release.

**Pull request merged**
